# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :datanode1 => {
    :box_name => "centos/7",
    :ip_addr => '192.168.11.102',
},
  :datanode2 => {
    :box_name => "centos/7",
    :ip_addr => '192.168.11.103',
},
  :datanode3 => {
    :box_name => "centos/7",
    :ip_addr => '192.168.11.104',
},

}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
      config.vm.define boxname do |box|
          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s
          box.vm.network "private_network", ip: boxconfig[:ip_addr]
           box.vm.provider :virtualbox do |vb|
             vb.customize ["modifyvm", :id, "--memory", "2048"]
          end
            box.vm.provision "shell", inline: <<-SHELL
              setenforce 0
              mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
              cat /vagrant/id_rsa.pub >> /root/.ssh/authorized_keys
              echo 192.168.11.101 ambari.local ambari>>/etc/hosts
              echo 192.168.11.102 datanode1.local datanode1>>/etc/hosts
              echo 192.168.11.103 datanode2.local datanode2>>/etc/hosts
              echo 192.168.11.104 datanode3.local datanode3>>/etc/hosts
              hostnamectl set-hostname $HOSTNAME.local
  	  SHELL
      end
  end
end
