# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :minio => {
    :box_name => "centos/7",
    :ip_addr => '192.168.11.101',
  },
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s
          box.vm.network "forwarded_port", guest: 9000, host: 59000
          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
             vb.customize ["modifyvm", :id, "--memory", "4096"]
          end

            box.vm.provision "shell", inline: <<-SHELL
              setenforce 0
              mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
              
              yum install vim wget -y
              wget https://dl.minio.io/server/minio/release/linux-amd64/minio -q -P /vagrant
              wget https://dl.minio.io/client/mc/release/linux-amd64/mc -q -P /vagrant
              chmod +x /vagrant/minio
              chmod +x /vagrant/mc
              mkdir /media/minio
              /vagrant/minio server /media/minio
  	  SHELL
      end
  end
end
